#!/usr/bin/env python

import sys

from cob_teacher.rqt_teacher import cob_teacher_plugin
from rqt_gui.main import Main

plugin = 'cob_teacher'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=cob_teacher_plugin.add_arguments))
